### PR TITLE
Handle Preprocessing for Descending Time Series Data

### PR DESCRIPTION
**Pull request by adai183**
## Detected Unintuitive Behaviour

I ran into a weird error when passing in a dataframe with a descending date index.

`ValueError: attempt to get argmax of an empty sequence`

## Root Cause

`autots.tools.shaping.df_cleanup` is returning an empty dataframe because the inferred frequency of `-1H` results in unexpected behaviour when filling missing dates.

Example:
Screenshot 2022-09-27 at 19 25 35

## Proposed Change

Let's make sure to sort the time series in ascending order at the beginning of the cleanup for additional robustness and avoid the mystery error message. This also guarantees compatibility with Prophet, which can handle unordered time series data.

### CODE REVIEW

**Comment by winedarksea** [comment]
Nice catch, thanks for noticing this. 
I will say that `long_to_wide` already has the exact same sort function, but only covers long style data import. Instead of duplicating the behavior for all data styles, what I just did in the dev branch of the AutoTS class was add it to the if else:
```
        # convert data to wide format
        if date_col is None and value_col is None:
            df_wide = pd.DataFrame(df).copy()
            assert (
                type(df_wide.index) is pd.DatetimeIndex
            ), "df index is not pd.DatetimeIndex"
            df_wide = df_wide.sort_index(ascending=True)  # THIS IS NEW
        else:
            df_wide = long_to_wide(
                df,
                date_col=self.date_col,
                value_col=self.value_col,
                id_col=self.id_col,
                aggfunc=self.aggfunc,
            )
```
Would this be sufficient for you?

**Comment by adai183** [comment]
@winedarksea of course! Makes a lot of sense.

**Comment by winedarksea** [comment]
I'd already committed that change when I made that comment. No point in merging twice, sorry!

**Comment by adai183** [comment]
@winedarksea No prob! Thanks! This would have been way to cheap to get props for this awesome project anyways. lol 
Happy to have connected. I will be a heavy user of AutoTS for the next weeks. Pointers towards meaningful contributions are very much appreciated.

**Comment by winedarksea** [comment]
Everyone always comments "and you've done that all by yourself!" in encounters (specifically past job interviews) and I am reluctant to go from being the sole author to just one of a crowd, which I would with any contributors.
At some point I will open the flood gates and let anyone and every contribute as is proper, probably after I've settled down the API a bit and released a 1.0. That said, I do really welcome feedback and suggestions.

**Pull request closed without merging**
